### ISSUE TITLE
[BUG] ScaffAngular doesn't seem to work from repository installation

### ISSUE THREAD

**Issue by GistCode** [suparngp/scaffAngular#9]
OSX Mac 
Webstorm 10
Scaffangular installed from repository

Error Message
cannot create class "org.weebly.generator.actions.CreateAction" [Plugin: org.weebly.generator]

Details
cannot create class "org.weebly.generator.actions.CreateAction" [Plugin: org.weebly.generator]
com.intellij.diagnostic.PluginException: cannot create class "org.weebly.generator.actions.CreateAction" [Plugin: org.weebly.generator]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:516)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:496)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:489)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
	at com.intellij.ide.actions.WeighingActionGroup.getChildren(WeighingActionGroup.java:61)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1310)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1303)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1303)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1318)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1297)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.c(ActionManagerImpl.java:1287)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:76)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1268)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.intellij.diagnostic.PluginException: org/weebly/generator/actions/CreateAction : Unsupported major.minor version 51.0 [Plugin: org.weebly.generator]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
	... 23 more
Caused by: java.lang.UnsupportedClassVersionError: org/weebly/generator/actions/CreateAction : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 29 more

**Comment by kether667** [comment]
scaffAngular is now build with java 7, please update JRE your IDE is running to 7 or 8.

You can check which JRE is currently used in Help -> About

**Comment by GistCode** [comment]
Thank you your fast response is highly appreciated,

Currently worked on making it work in a mac

**Comment by GistCode** [comment]
?Thanks! It worked!

________________________________

**Comment by GistCode** [comment]
I appreciate all the work that went into this, 

I'd just like to suggest to add an empty array during the initialization of a module

at the moment after creating a component it looks like

angular.module('modulename')
      .controller('Dashboard',function($scope){
});

but it creates an error I think that would probably confuse your new users,

this is the expected result to make it work

angular.module('modulename', [] )
      .controller('Dashboard',function($scope){
});

Thank you

**Comment by kether667** [comment]
Usually you have your module already created and you just want to add more components to it. 

Updated readme to notify about JRE 7 requirement,
Created #10 to solve module initialization use case

closing now
